Name = input("Enter your fullname : ")
Class_Name = input("Enter your class: ")
Div = input("Enter your Division: ")
Roll_Num = input("Enter your Roll Num: ")
Mobile_Num = input("Enter your Mobile Number: ")
Email_Id = input("Enter your Email i'd: ")
F = open('My-file','a')
F.write(f'Name: {Name} \n')
F.write(f'Class: {Class_Name}\n')
F.write(f'Division: {Div} \n')
F.write(f'Roll num: {Roll_Num}\n')
F.write(f'Mobile num: {Mobile_Num}\n')
F.write(f'Email Id: {Email_Id}\n')
F.close()
F = open('My-file','r')
print(F.read())
F.close()
